import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Formulário de Cadastro",
  description: "Generated by create next app",
  
};

export default function RootLayout({ children }) {
  return (
    
    <html lang="pt-br">
      <head>
      </head>
      <body className={inter.className}>{children}</body>
    </html>
  );
}
